import {ProviderCache,boundedJSON} from './server-cache';
import {array,record,num,str,type Bounds,type WorldRecord} from './types';
const cache=new ProviderCache('open-meteo',600000,5000,24);
export function weatherGrid(b:Bounds){const points:number[][]=[];const n=b[2]-b[0]>30?3:4;for(let y=0;y<n;y++)for(let x=0;x<n;x++)points.push([+(b[1]+(b[3]-b[1])*(y+.5)/n).toFixed(3),+(b[0]+(b[2]-b[0])*(x+.5)/n).toFixed(3)]);return points;}
export function normalizeWeather(body:unknown,points:number[][],now=new Date().toISOString()):WorldRecord[]{return (Array.isArray(body)?body:[body]).slice(0,16).flatMap((v,i)=>{
 const r=record(v),c=record(r.current),h=record(r.hourly),p=points[i];if(!p||!c.time)return [];const at=`${str(c.time)}Z`;if(!Number.isFinite(Date.parse(at)))return [];
 const hi=array(h.time).findIndex(t=>`${t}`.slice(0,13)===str(c.time).slice(0,13));
 return [{id:`open-meteo:${p.join(',')}`,provider:'Open-Meteo',name:`Weather model ${p.join(', ')}`,domain:'weather',subtype:'WEATHER',lat:p[0],lon:p[1],observed_at:at,fetched_at:now,url:'https://open-meteo.com/en/docs',evidence_state:'DERIVED',confidence:null,extraction_method:'best_match model current conditions; hourly visibility',geometry_precision:'representative',location_precision:'APPROXIMATE',source_license:'CC BY 4.0; free API non-commercial',source_attribution:'Weather data by Open-Meteo',properties:{temperature_c:num(c.temperature_2m),precipitation_mm:num(c.precipitation),cloud_percent:num(c.cloud_cover),pressure_hpa:num(c.pressure_msl),wind_speed_ms:num(c.wind_speed_10m),wind_from_deg:num(c.wind_direction_10m),wind_gust_ms:num(c.wind_gusts_10m),visibility_m:hi<0?null:num(array(h.visibility)[hi]),visibility_valid_at:hi<0?null:`${array(h.time)[hi]}Z`,model:'best_match',model_run_at:null,valid_at:at,interval_seconds:c.interval,units:r.current_units,hourly_units:r.hourly_units,requested_lat:p[0],requested_lon:p[1],model_lat:r.latitude,model_lon:r.longitude}} satisfies WorldRecord];
 });}
export async function weather(b:Bounds){const points=weatherGrid(b);return cache.get(JSON.stringify(points),async()=>{const q=new URLSearchParams({latitude:points.map(p=>p[0]).join(','),longitude:points.map(p=>p[1]).join(','),current:'temperature_2m,precipitation,cloud_cover,pressure_msl,wind_speed_10m,wind_direction_10m,wind_gusts_10m',hourly:'visibility',forecast_days:'1',wind_speed_unit:'ms',timezone:'UTC'});const key=process.env.OPEN_METEO_API_KEY;if(key)q.set('apikey',key);const body=await boundedJSON(`https://${key?'customer-api':'api'}.open-meteo.com/v1/forecast?${q}`,{},1024*1024);return {records:normalizeWeather(body,points),status:'AVAILABLE'};});}
export interface RadarFrame {time:number;path:string}
const radarCache=new ProviderCache('rainviewer',120000,1000,1);
export async function radar(){return radarCache.get('metadata',async()=>{const body=record(await boundedJSON('https://api.rainviewer.com/public/weather-maps.json',{},100000));const frames=array(record(body.radar).past).map(record).filter(r=>typeof r.time==='number'&&/^\/v2\/radar\/[a-zA-Z0-9_-]+$/.test(str(r.path))).map(r=>({time:Number(r.time)*1000,path:str(r.path)})).slice(-18);return {frames,status:'AVAILABLE',attribution:'RainViewer',maxzoom:7};});}
export function radarAt(frames:RadarFrame[],at:number){if(!frames.length||at<frames[0].time||at>frames.at(-1)!.time+600000)return null;return frames.filter(f=>f.time<=at).at(-1)||null;}
