const { test, before, after } = require('node:test');
const assert = require('node:assert/strict');
const { randomUUID } = require('node:crypto');
const { Pool } = require('pg');
const express = require('express');
const { OntologyStore } = require('../store');
const { worldInput, saveWorld } = require('../../intelligence/world');
const { AirThreatService, query } = require('../../intelligence/air-service');
const { intelligenceRoutes } = require('../../intelligence/routes');
const { TimelineService } = require('../../intelligence/timeline');
const { updateCapabilities } = require('../../intelligence/air-registry');
const schema = `air_test_${randomUUID().replaceAll('-', '')}`;
let admin, store, air, server, url;
const now = Date.now() - 60000, iso = n => new Date(n).toISOString();
function input(id, extra = {}) { return { id: `alerts-in-ua:${id}`, name: 'Fixture civil alert', provider: 'alerts.in.ua', record: { domain: 'conflict', subtype: 'AIR_RAID_ALERT', lat: null, lon: null, location_precision: 'DISTRICT', geometry_precision: 'representative', observed_at: iso(now - 600000), fetched_at: iso(now - 600000), properties: { source_class: 'OFFICIAL', alert_status: 'ACTIVE', provider_raw_type: 'air_raid', area_ids: ['alerts-in-ua:123'], area_name: 'Fixture district' }, ...extra } }; }
async function save(i, trusted = true) { const p = worldInput(i, trusted); return store.transaction(db => saveWorld(store, db, p)); }
before(async () => { admin = new Pool(); await admin.query(`CREATE SCHEMA ${schema}`); store = new OntologyStore(new Pool({ options: `-c search_path=${schema},public` })); await store.migrate(); await store.migrate(); air = new AirThreatService(store); const app = express(); app.use('/intelligence', intelligenceRoutes(store)); app.use((e, req, res, next) => res.status(e.status || 400).json({ error: e.message })); server = app.listen(0, '127.0.0.1'); await new Promise(r => server.once('listening', r)); url = `http://127.0.0.1:${server.address().port}/intelligence`; });
after(async () => { await new Promise(r => server.close(r)); await store.pool.end(); await admin.query(`DROP SCHEMA ${schema} CASCADE`); await admin.end(); });
test('empty AOI is no coverage, never all clear', async () => { const s = await air.state({ bbox: '10,10,11,11' }); assert.equal(s.official_status, 'UNKNOWN'); assert.equal(s.coverage, 'INSUFFICIENT_REPORT_COVERAGE'); assert.equal(s.reports.length, 0); });
test('missing credentials persist independently from source network failures', async () => { await updateCapabilities(store, [{ id: 'israel-hfc', name: 'Official provider fixture', credential_state: 'DOCUMENTED_API_REQUIRED', coverage: ['IL'], connected: false }]); const r = (await store.pool.query("SELECT * FROM intelligence_sources WHERE id='world:israel-hfc'")).rows[0]; assert.equal(r.credential_state, 'DOCUMENTED_API_REQUIRED'); assert.equal(r.consecutive_failures, 0); assert.equal(r.last_failure_at, null); assert.equal(r.enabled, false); });
test('explicit active to clear lifecycle preserves historical state and observation evidence', async () => { const id = await save(input('1')); const active = await air.state({ admin: 'alerts-in-ua:123', at: iso(now - 590000) }); assert.equal(active.official_status, 'ACTIVE'); await save(input('1', { subtype: 'ALL_CLEAR', observed_at: iso(now - 300000), fetched_at: iso(now - 300000), properties: { alert_status: 'CLEAR', provider_raw_type: 'air_raid', area_ids: ['alerts-in-ua:123'], area_name: 'Fixture district' } })); const clear = await air.state({ admin: 'alerts-in-ua:123', at: iso(now - 290000) }); assert.equal(clear.official_status, 'CLEAR'); assert.equal((await air.state({ admin: 'alerts-in-ua:123', at: iso(now - 580000) })).official_status, 'ACTIVE'); assert.equal(clear.official[0].object_id, id); assert.equal(clear.reports[0].provider_raw_type, 'air_raid'); assert.equal(clear.reports[0].source_class, 'OFFICIAL'); });
test('confirmation gaps stay unknown and future analysis is rejected', async () => { await save(input('2')); const s = await air.state({ admin: 'alerts-in-ua:123', at: iso(now + 600000) }).catch(e => e); assert.ok(s instanceof Error); const later = await air.state({ admin: 'alerts-in-ua:123', at: iso(Date.now()) }); assert.equal(later.official_status, 'UNKNOWN'); });
test('client-supplied official claim cannot create official status', async () => { await save(input('3', { fetched_at: iso(now), observed_at: iso(now) }), false); const rows = (await store.pool.query('SELECT * FROM intelligence_official_alert_states')).rows; assert.equal(rows.length, 3); });
test('public acoustic reports persist and replay without inferring source location', async () => { const i = input('5', { subtype: 'HEARD_EXPLOSION', lat: 50, lon: 30, observed_at: iso(now), fetched_at: iso(now), properties: { provider_raw_type: 'heard explosion', raw_description: 'Fixture only: heard a sound' } }); i.id = 'public-report:fixture5'; i.provider = 'Public report'; const id = await save(i, false); const s = await air.state({ bbox: '29,49,31,51', at: iso(now + 1000) }); const r = s.reports.find(r => r.object_id === id); assert.equal(r.source_class, 'PUBLIC_REPORT'); assert.equal(r.type, 'HEARD_EXPLOSION'); assert.equal((await air.acoustic({ observation_id: r.id, at: iso(now + 1000), scenario: true, reference_db: 100, reference_m: 10, background_db: 40 })).status, 'UNKNOWN_SOURCE_POSITION'); const timeline = await new TimelineService(store).state({ at: iso(now + 1000), domains: 'conflict' }); assert.ok(timeline.items.some(r => r.object_id === id)); });
test('known event forward scenario carries retained weather evidence and strict inputs', async () => { const i = input('6', { subtype: 'EXPLOSION_REPORT', lat: 50, lon: 30, observed_at: iso(now), fetched_at: iso(now), properties: { provider_raw_type: 'explosion report' } }); i.id = 'public-report:fixture6'; i.provider = 'Public report'; const id = await save(i, false); await save({ id: 'open-meteo:50,30', name: 'Fixture model cell', provider: 'Open-Meteo', record: { domain: 'weather', subtype: 'WEATHER', lat: 50, lon: 30, observed_at: iso(now - 1000), fetched_at: iso(now), location_precision: 'APPROXIMATE', geometry_precision: 'representative', properties: { wind_speed_ms: 4, wind_from_deg: 270, temperature_c: 20, humidity_percent: 60 } } }, false); const observation = (await store.pool.query("SELECT id FROM intelligence_observations WHERE object_id=$1 AND event_type='CONFLICT_REPORT'", [id])).rows[0].id; const result = await air.acoustic({ observation_id: observation, at: iso(now + 1000), scenario: true, reference_db: 100, reference_m: 10, background_db: 40 }); assert.equal(result.status, 'SCENARIO_ONLY'); assert.equal(result.weather_state, 'AVAILABLE'); assert.ok(result.weather_observation_id); assert.ok(result.provenance.some(p => p.provider === 'Open-Meteo' && p.kind === 'derived')); await assert.rejects(air.acoustic({ observation_id: observation, scenario: 'true' }), /scenario/); });
test('state hard bounds, AOI filters and malformed requests enforced by HTTP', async () => { for (const q of ['bbox=-180,-90,180,90', 'bbox=1,2,3,4&limit=100000', 'bbox=1,2,3,4&at=bad', 'admin=name only', 'bbox=1,2,3,4&url=http://localhost']) {
    assert.equal((await fetch(`${url}/air-threat/state?${q}`)).status, 400);
} assert.equal((await fetch(`${url}/air-threat/acoustic`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ observation_id: randomUUID() }) })).status, 404); assert.throws(() => query({ bbox: '170,0,-170,5' })); });
