'use client';
import {useLocale as useUILocale} from '@/lib/i18n';
import AddToCaseButton from './AddToCaseButton';
import { useEffect, useState } from 'react';
import { useAirThreat } from './AirThreatProvider';
import { useWorldReplay } from './WorldReplayProvider';
import { DISCLAIMER, REPORT_GROUPS, validAOI, reportGroup, type AirReport } from '@/lib/air-threat/types';
import { INVESTIGATION_ACTIONS, type InvestigationIntent } from '@/lib/investigation';
import EvidenceView from './EvidenceView';
import AirAcousticPanel from './AirAcousticPanel';
import PublicAcousticReport from './PublicAcousticReport';
export default function AirThreatPanel({ onObject, onFocus }: {
    onObject: (id: string, intent: InvestigationIntent) => void;
    onFocus: (lat: number, lon: number) => void;
}) {
  const {t:uiText}=useUILocale();
    const a = useAirThreat(), replay = useWorldReplay(), [name, setName] = useState(a.aoi?.name || ''), [bbox, setBBox] = useState(a.aoi?.bbox || ''), [admin, setAdmin] = useState(a.aoi?.admin || ''), [formError, setFormError] = useState(''), [areas, setAreas] = useState<{
        key: string;
        name: string;
    }[]>([]), [count, setCount] = useState(30);
    useEffect(() => { const c = new AbortController(); void fetch('/api/intelligence/air-threat/areas', { signal: c.signal }).then(r => r.json()).then(r => setAreas(r.items || [])).catch(() => { }); return () => c.abort(); }, []);
    const selected = a.selected && 'type' in a.selected ? a.selected : null, cluster = a.selected && 'report_ids' in a.selected ? a.selected : null;
    const choose = (r: AirReport) => { a.select(r); a.setAcoustic(null); if (r.lat != null && r.lon != null)
        onFocus(r.lat, r.lon); };
    const apply = () => { const next = { name: name.trim(), bbox, admin }; if (!validAOI(next)) {
        setFormError('Choose a named AOI up to 30° across (west,south,east,north), or an exact provider administrative ID.');
        return;
    } setFormError(''); a.setAOI(next); setCount(30); };
    return <section role="dialog" aria-label={uiText("Civilian air threat awareness")} className="absolute left-16 top-24 z-[420] w-[420px] max-w-[calc(100vw-90px)] max-h-[78vh] overflow-auto rounded border border-amber-400/50 bg-slate-950/95 p-4 shadow-xl text-slate-200 font-mono text-[11px] space-y-3">
 <div className="sticky -top-4 z-10 bg-slate-950 pt-3 pb-2 border-b border-amber-400/30"><header className="flex gap-2"><h2 className="text-amber-300 flex-1 tracking-wider">{uiText("CIVILIAN AIR THREAT AWARENESS")}</h2><button aria-label={uiText("Close civilian awareness")} onClick={() => a.setOpen(false)}>×</button></header><p className="text-amber-100">{uiText(DISCLAIMER)}</p><strong className="block">{uiText("No reports does not mean no threat.")}</strong></div>
 <form onSubmit={e => { e.preventDefault(); apply(); }} className="space-y-1"><label className="block">{uiText("AOI / city / region label")}<input aria-label={uiText("AOI name")} maxLength={100} className="w-full bg-slate-900 p-1 border border-slate-700" value={name} onChange={e => setName(e.target.value)}/></label><label className="block">{uiText("Bounds west,south,east,north")}<input aria-label={uiText("AOI bounds")} className="w-full bg-slate-900 p-1 border border-slate-700" value={bbox} onChange={e => setBBox(e.target.value)}/></label><button type="button" className="underline" onClick={() => { setBBox(a.viewport); if (!name)
        setName('Selected map area'); }}>{uiText("Use current viewport")}</button><p>{uiText("Use the map Search to locate a city, then select its viewport. Labels do not establish administrative identity.")}</p><label className="block">{uiText("Official administrative ID (optional)")}<input list="civilian-areas" aria-label={uiText("Official administrative ID")} placeholder="provider:source-region-id" className="w-full bg-slate-900 p-1 border border-slate-700" value={admin} onChange={e => setAdmin(e.target.value)}/><datalist id="civilian-areas">{areas.map(r => <option key={`${r.key}:${r.name}`} value={r.key}>{r.name}</option>)}</datalist></label><button className="border border-amber-300/50 p-2">{uiText("Apply AOI")}</button>{formError && <p role="alert">{formError}</p>}</form>
 {a.error && <p role="alert">{a.error}</p>}{a.busy && <p role="status">{uiText("Refreshing retained signals…")}</p>}{!a.aoi && <p>{uiText("Select an AOI to inspect retained reports.")}</p>}
 {a.state && <><p>{replay.state.mode === 'replay' ? uiText("REPLAY") : uiText("LIVE")}{" "}{uiText("· analysis at")}{" "}{a.state.at}{" "}{uiText("· refresh at most every 10 seconds")}</p><strong className="block text-amber-300">{uiText("OFFICIAL STATUS:")}{" "}{uiText(a.state.official_status)}</strong><p>{uiText("This status covers matched retained alert records only; it is not a comprehensive regional all-clear service.")}</p><p>{uiText("15 min:")}{" "}{a.state.counts.last15}{" "}{uiText("· 30 min:")}{" "}{a.state.counts.last30}{" "}{uiText("· 60 min:")}{" "}{a.state.counts.last60}</p><p>{uiText("Official:")}{" "}{a.state.counts.classes.OFFICIAL}{" "}{uiText("· Structured OSINT:")}{" "}{a.state.counts.classes.STRUCTURED_OSINT}{" "}{uiText("· Public:")}{" "}{a.state.counts.classes.PUBLIC_REPORT}</p><strong>{uiText(a.state.coverage)}</strong><p>{a.state.truncated ? 'PARTIAL RESULTS — narrow the AOI.' : ''}</p>
 <details><summary>{uiText("Provider coverage / gaps")}</summary>{a.state.providers.map(p => <p key={p.id}>{p.name}: {p.credential_state} · {p.status} · {p.latest_update || 'No retained check'}</p>)}{a.state.coverage_gaps.map(g => <p key={g}>{uiText(String(g))}</p>)}<p>{uiText("Provider health reflects current checks; historical coverage is not inferred from today's health.")}</p></details>
 {a.state.official.map(o => <details key={o.id} className="border-l-2 border-amber-300 pl-2"><summary>{uiText("OFFICIAL ·")}{" "}{o.status} · {o.canonical_name}</summary><p>{uiText("Confirmed through")}{" "}{o.confirmed_until}{" "}{uiText("· Source")}{" "}{o.source_time}</p><p>{uiText("Reported types:")}{" "}{JSON.stringify(o.data?.threat_types || [])}</p><button className="underline" onClick={() => onObject(o.object_id, 'history')}>{uiText("Alert history")}</button><EvidenceView items={o.provenance || []}/></details>)}
 <fieldset><legend>{uiText("Report categories")}</legend><div className="grid grid-cols-2">{REPORT_GROUPS.map(g => <label key={g}><input type="checkbox" checked={a.groups.includes(g)} onChange={e => a.setGroups(old => e.target.checked ? [...old, g] : old.filter(x => x !== g))}/> {uiText(String(g))}</label>)}</div></fieldset><label className="block"><input type="checkbox" checked={a.heat} onChange={e => a.setHeat(e.target.checked)}/>{" "}{uiText("Recent-report heatmap")}</label><p>{uiText("Concentration of retained reports, weighted by age, reported precision and source-family diversity. Not weapon probability. Gold = official, blue = OSINT, violet = public. Opacity denotes age.")}</p><label className="block"><input type="checkbox" checked={a.envelopes} onChange={e => a.setEnvelopes(e.target.checked)}/>{" "}{uiText("Activity envelopes")}</label><p>{uiText("ACTIVITY ENVELOPE — recent reported activity, not tracked weapon position.")}</p>
 <p>{uiText("Icons denote source claims, not detected objects. Cyan halos mark sound-report areas, not audibility or a danger radius.")}</p><h3 className="text-amber-200">{uiText("Report clusters · DERIVED")}</h3>{!a.state.clusters.length && <p>{uiText("No compatible retained cluster for this AOI/time.")}</p>}{a.state.clusters.map(c => <button key={c.id} className="block underline text-left py-1" onClick={() => { a.select(c); a.setAcoustic(null); }}>{uiText(c.kind)} · {c.report_count}{" "}{uiText("reports ·")}{" "}{c.state}</button>)}
 <h3 className="text-amber-200">{uiText("Retained reports")}</h3>{a.state.reports.filter(r => a.groups.includes(reportGroup(r.type))).slice(0, count).map(r => <button key={r.id} className="block text-left border-b border-slate-800 py-2 w-full" onClick={() => choose(r)}>{uiText(r.type)} · {uiText(r.source_class)}<br />{r.name} · {r.at}<br />{uiText(r.precision)} · {r.provider}</button>)}{a.state.reports.length > count && <button className="underline" onClick={() => setCount(n => n + 30)}>{uiText("Show next 30 retained reports")}</button>}{!a.state.reports.length && <p>{uiText("No retained reports in this AOI/time. This is not ALL CLEAR.")}</p>}</>}
 {cluster && <section className="border-t border-violet-300 pt-2"><h3>{uiText("WHY AM I SEEING THIS? · DERIVED")}</h3><AddToCaseButton analysis={{kind:'cluster',cluster_id:cluster.id,parameters:{at:a.state?.at,...(a.aoi?.bbox?{bbox:a.aoi.bbox}:{}),...(a.aoi?.admin?{admin:a.aoi.admin}:{})}}}/><p>{cluster.model_version} · {cluster.from} — {cluster.to}</p><p>{cluster.match_method} · {cluster.precision.join(' / ')}</p><p>{cluster.explanation}</p><p>{cluster.unique_signals}{" "}{uiText("unique lineage signals · families:")}{" "}{cluster.source_families.join(', ')}</p><p>{uiText("Independent sources:")}{" "}{cluster.independent_sources ?? uiText("Unknown")}. {cluster.independence_note}</p><pre className="whitespace-pre-wrap">{JSON.stringify(cluster.assumptions, null, 2)}</pre>{a.state?.reports.filter(r => cluster.report_ids.includes(r.id)).map(r => <button className="block underline py-1" key={r.id} onClick={() => choose(r)}>{uiText(r.source_class)} · {r.provider} · {r.at} · {uiText(r.type)}</button>)}</section>}
 {selected && <section className="border-t border-cyan-300 pt-2 space-y-2"><h3>{selected.name}</h3><p>{uiText(selected.source_class)} · {uiText(selected.type)}{" "}{uiText("· raw:")}{" "}{selected.provider_raw_type}</p><p>{uiText(selected.precision)} · {selected.precision === 'EXACT_SOURCE_COORDINATE' ? 'Source coordinate, not independently verified' : 'rendered_as_representative_point=true'}</p><div className="flex flex-wrap gap-2">{INVESTIGATION_ACTIONS.map(action => <button className="underline" key={action.intent} onClick={() => onObject(selected.object_id, action.intent)}>{uiText(String(action.label))}</button>)}<button className="underline" onClick={() => replay.jump(Date.parse(selected.at))}>{uiText("Jump to global timeline")}</button></div><AddToCaseButton reference={{kind:'observation',id:selected.id}}/><EvidenceView items={selected.provenance}/><details><summary>{uiText("Original metadata / source fields")}</summary><pre className="whitespace-pre-wrap break-words">{JSON.stringify(selected.data, null, 2)}</pre></details>{['EXPLOSION_REPORT', 'AIRSTRIKE', 'MILITARY_STRIKE', 'INTERCEPTION_REPORT'].includes(selected.type) && <AirAcousticPanel key={selected.id} report={selected}/>}</section>}
 <PublicAcousticReport />
 </section>;
}
