'use client';
import { useCallback, useEffect, useRef, useState } from 'react';
import { intelligenceRequest, displayTime, type Correlation, type Page, type InvestigationMapFocus } from '@/lib/intelligence';
import IntelligencePanelShell, { intelButton } from './IntelligencePanelShell';
import EvidenceView from './EvidenceView';
export default function CorrelationsPanel({ onClose, onMap, onObject }: { onClose: () => void; onMap: (focus: InvestigationMapFocus) => void; onObject: (id: string) => void }) {
  const [status, setStatus] = useState('ACTIVE'), [items, setItems] = useState<Correlation[]>([]), [cursor, setCursor] = useState<string | null>(null), [selected, setSelected] = useState<Correlation | null>(null), [busy, setBusy] = useState(false), [error, setError] = useState('');
  const detailAbort = useRef<AbortController | null>(null), listGeneration = useRef(0);
  const [truncated,setTruncated]=useState(false);
  const load = useCallback(async (signal: AbortSignal, after?: string) => { const version=++listGeneration.current;setBusy(true); setError(''); try { const result = await intelligenceRequest<Page<Correlation> & {truncated?:boolean}>(`correlations?status=${status}&limit=40${after ? `&cursor=${after}` : ''}`, signal); if (signal.aborted || version!==listGeneration.current) return; setTruncated(!!result.truncated);setItems(old => after ? [...old, ...result.items] : result.items); setCursor(result.next_cursor); } catch (e) { if (!signal.aborted && version===listGeneration.current) setError(e instanceof Error ? e.message : 'Correlations unavailable'); } finally { if (!signal.aborted && version===listGeneration.current) setBusy(false); } }, [status]);
  useEffect(() => { const c = new AbortController(); const start = setTimeout(() => void load(c.signal), 0); const t = setInterval(() => void load(c.signal), 60000); return () => { c.abort(); clearTimeout(start); detailAbort.current?.abort(); clearInterval(t); }; }, [load]);
  async function open(id: string) { detailAbort.current?.abort(); const c = new AbortController(); detailAbort.current = c; setBusy(true); setError(''); try { const row = await intelligenceRequest<Correlation>(`correlations/${id}`, c.signal); if (!c.signal.aborted) setSelected(row); } catch (e) { if (!c.signal.aborted) setError(e instanceof Error ? e.message : 'Evidence unavailable'); } finally { if (!c.signal.aborted) setBusy(false); } }
  async function dismiss() { if (!selected) return; setBusy(true); try { await intelligenceRequest(`correlations/${selected.id}/dismiss`, undefined, 'POST'); setSelected({ ...selected, status: 'DISMISSED' }); await open(selected.id); await load(new AbortController().signal); } catch (e) { setError(e instanceof Error ? e.message : 'Dismiss failed'); } finally { setBusy(false); } }
  return <IntelligencePanelShell title="CORRELATIONS / RELATED SIGNALS" onClose={onClose}><div className="p-3 text-xs border-b border-[var(--border-primary)] flex flex-wrap gap-3 items-center"><select aria-label="Correlation status" className="bg-[var(--bg-secondary)] p-2" value={status} onChange={e => setStatus(e.target.value)}>{['ACTIVE', 'EXPIRED', 'DISMISSED', 'all'].map(s => <option key={s}>{s}</option>)}</select><button className={intelButton} disabled={busy} onClick={() => void load(new AbortController().signal)}>Refresh</button><span className="text-slate-400">Deterministic screening · potential risk, not confirmed impact or causation</span></div>
    {truncated&&<p className="p-3 text-xs text-amber-300">Showing the newest 2,000 matches. Narrow the status or refresh to start a new snapshot.</p>}{error && <p role="alert" className="p-3 text-xs text-red-300">{error}</p>}{busy && <p role="status" className="px-3 text-xs">Loading…</p>}
    <div className="flex-1 min-h-0 flex flex-col md:flex-row"><div className="md:w-2/5 overflow-auto p-3 space-y-2 border-r border-[var(--border-primary)]">{items.map(c => <button key={c.id} onClick={() => void open(c.id)} className={`w-full text-left rounded border p-3 text-xs ${selected?.id === c.id ? 'border-[var(--gold-primary)]' : 'border-[var(--border-primary)]'} hover:bg-[var(--bg-secondary)]`}><div className="text-[var(--gold-primary)] break-words">{c.correlation_type.replaceAll('_', ' ')}</div><div className="my-1">{c.strength} SUPPORT · {c.status}</div><div className="text-slate-400">{displayTime(c.last_confirmed_at)} · {c.related_object_ids.length} objects</div><p className="mt-2 line-clamp-3">{c.explanation}</p></button>)}{!busy && !items.length && <p className="text-xs text-slate-400">No correlations match this status. Rules require sufficient fresh evidence. Absence of a signal does not establish safety.</p>}{cursor && items.length < 2000 && <button className={intelButton} disabled={busy} onClick={() => void load(new AbortController().signal, cursor)}>Next correlations</button>}</div>
      <aside className="md:w-3/5 overflow-auto p-4 space-y-3 text-xs">{selected ? <><h3 className="text-[var(--gold-primary)]">WHY THIS WAS FLAGGED</h3><p>{selected.explanation}</p><div>{selected.strength} RULE SUPPORT · DERIVED · numeric confidence not assigned</div><ul className="list-disc pl-4 space-y-1">{selected.rationale.facts.map(f => <li key={f}>{f}</li>)}</ul><p className="text-slate-400">{selected.rationale.method}</p><div>Rule: {selected.rule_id} v{selected.rule_version}</div><div>Window: {displayTime(selected.window_start)} — {displayTime(selected.window_end)}</div><div>Last confirmed: {displayTime(selected.last_confirmed_at)}</div><div>Expires: {displayTime(selected.expires_at)}</div>
        <div className="flex gap-2"><button className={intelButton} disabled={!selected.geographic_context.center} onClick={() => { const p = selected.geographic_context.center!; onMap({ lat: p.lat, lng: p.lon, label: selected.correlation_type, points: selected.geographic_context.points.map(p => ({ lat: p.lat, lng: p.lon })) }); }}>Show on map</button><button className={intelButton} disabled={busy || selected.status === 'DISMISSED'} onClick={() => void dismiss()}>Dismiss signal</button></div>
        <div className="flex gap-2 flex-wrap">{selected.objects?.map(o => <button key={o.id} className={intelButton} onClick={() => onObject(o.id)}>Graph: {o.canonical_name}</button>)}</div>
        {selected.evidence?.map((e, i) => <details key={i} open className="border border-[var(--border-primary)] rounded p-2"><summary className="cursor-pointer text-cyan-300">{e.role} · {displayTime(e.observed_at)}</summary><pre className="whitespace-pre-wrap break-words text-[10px] py-2">{JSON.stringify(e.data, null, 2)}</pre><EvidenceView items={e.provenance} /></details>)}
        <details><summary className="cursor-pointer">Rule thresholds</summary><pre className="whitespace-pre-wrap">{JSON.stringify(selected.rationale.thresholds, null, 2)}</pre></details><details><summary className="cursor-pointer">Lifecycle history</summary>{selected.lifecycle?.map((e, i) => <p className="my-2" key={i}>{displayTime(e.changed_at)} · {e.status} · {e.reason}</p>)}</details>
      </> : <p className="text-slate-400">Select a correlation to inspect its evidence, related objects and location.</p>}</aside>
    </div></IntelligencePanelShell>;
}
