'use client';
import {useState} from 'react';
import {useWorldReplay} from './WorldReplayProvider';
import {REPLAY_DOMAINS,REPLAY_SPEEDS,sliderValue,sliderTime,jumpReplay,type ReplayItem} from '@/lib/replay';
import {INVESTIGATION_ACTIONS,type InvestigationIntent} from '@/lib/investigation';
import EvidenceView from './EvidenceView';
const button='border border-[var(--gold-primary)]/40 rounded px-2 py-1 disabled:opacity-40 hover:bg-[var(--gold-primary)]/15';
const utc=(at:number|string)=>new Date(at).toISOString().replace('T',' ').slice(0,19)+' UTC';
export default function GlobalTimeline({onFocus,onObject}:{onFocus:(lat:number,lon:number)=>void;onObject:(id:string,intent:InvestigationIntent)=>void}){
 const r=useWorldReplay(),s=r.state;
 const [custom,setCustom]=useState(false),[from,setFrom]=useState(''),[to,setTo]=useState(''),[rangeError,setRangeError]=useState(''),[bucketContext,setBucketContext]=useState('');
 const setAt=(at:number)=>r.setState(v=>jumpReplay(v,Math.max(v.from,Math.min(v.to,at))));
 const choose=(item:ReplayItem)=>{r.select(item);if(item.lat!=null&&item.lon!=null)onFocus(item.lat,item.lon);};
 const preset=(hours:number,now:number)=>{r.setState(v=>({...v,from:now-hours*3600000,to:now,at:Math.max(now-hours*3600000,Math.min(now,v.at)),playing:false}));setCustom(false);};
 return <>
 <section aria-label="Global Timeline" tabIndex={0} onKeyDown={e=>{if(s.mode!=='replay'||['INPUT','TEXTAREA','SELECT'].includes((e.target as HTMLElement).tagName))return;if([' ','ArrowLeft','ArrowRight','End'].includes(e.key)){e.preventDefault();e.stopPropagation();if(e.key===' ')r.setState(v=>({...v,playing:!v.playing}));else if(e.key==='End')r.live();else setAt(s.at+(e.key==='ArrowLeft'?-60000:60000));}}} className={`absolute z-[450] bottom-12 left-1/2 -translate-x-1/2 rounded-lg border ${s.mode==='replay'?'border-cyan-400':'border-[var(--gold-primary)]/50'} bg-[var(--bg-primary)]/95 text-[var(--text-primary)] font-mono text-[11px] shadow-xl ${s.open?'w-[min(900px,calc(100vw-100px))]':'w-auto'}`}>
  <div className="flex flex-wrap items-center gap-2 p-2"><button className="font-bold text-[var(--gold-primary)]" aria-expanded={s.open} onClick={()=>r.setState(v=>({...v,open:!v.open}))}>GLOBAL TIMELINE {s.open?'▾':'▴'}</button><strong className={s.mode==='replay'?'text-cyan-300':'text-emerald-300'}>{s.mode==='live'?'LIVE / NOW':`REPLAY · ${utc(s.at)}`}</strong>{s.mode==='replay'&&<button className={button} onClick={r.live}>RETURN TO LIVE</button>}</div>
  {s.open&&<div className="px-3 pb-3 space-y-2 max-h-[45vh] overflow-auto">
   <div className="flex flex-wrap gap-2 items-center">{[1,6,24,168].map(h=><button key={h} className={button} onClick={()=>preset(h,Date.now())}>{h===168?'7d':`${h}h`}</button>)}<button className={button} onClick={()=>setCustom(!custom)}>Custom range</button><span>{utc(s.from)} — {utc(s.to)}</span></div>
   {custom&&<form className="flex gap-2 flex-wrap" onSubmit={e=>{e.preventDefault();const a=Date.parse(from),b=Date.parse(to);if(!Number.isFinite(a)||!Number.isFinite(b)||a>=b||b>Date.now()||b-a>31*86400000){setRangeError('Choose a past range of at most 31 days (inputs use local time).');return;}setRangeError('');r.setState(v=>({...v,from:a,to:b,at:Math.max(a,Math.min(b,v.at)),playing:false}));}}><label>From <input aria-label="Replay range from" type="datetime-local" value={from} onChange={e=>setFrom(e.target.value)} className="bg-slate-800"/></label><label>To <input aria-label="Replay range to" type="datetime-local" value={to} onChange={e=>setTo(e.target.value)} className="bg-slate-800"/></label><button className={button}>Apply range</button>{rangeError&&<span role="alert">{rangeError}</span>}</form>}
   <input aria-label="Replay time slider" type="range" min={0} max={1000} step={1} value={sliderValue(s.at,s)} className="w-full accent-cyan-300" onChange={e=>setAt(sliderTime(Number(e.target.value),s))}/>
   <div className="relative h-6 bg-slate-800/50" aria-label="Retained event buckets">{r.coverage?.buckets.map(b=><button key={b.index} title={`${utc(b.at)} · ${b.count} observations · ${Object.keys(b.domains).join(', ')}`} aria-label={`Timeline bucket ${b.index}: ${b.count} observations`} style={{left:`${b.index/96*100}%`,height:`${Math.min(24,7+Math.log2(b.count+1)*3)}px`}} className="absolute bottom-0 w-[0.9%] min-w-1 bg-cyan-400/70 hover:bg-amber-300" onClick={()=>{setAt(Date.parse(b.at));r.select(null);setBucketContext(`${b.name} · ${b.count} retained records · ${utc(b.at)}`);onFocus(b.lat,b.lon);}}/>)}</div>
   {bucketContext&&<p className="text-cyan-300">{bucketContext}</p>}
   <div className="flex gap-2 items-center flex-wrap"><button className={button} onClick={()=>setAt(s.at-60000)} aria-label="Step backward one minute">−1 min</button><button className={button} disabled={r.busy||!!r.error} onClick={()=>r.setState(v=>({...v,mode:'replay',playing:!v.playing,at:v.at>=v.to?v.from:v.at}))}>{s.playing?'Pause':'Play'}</button><button className={button} onClick={()=>setAt(s.at+60000)} aria-label="Step forward one minute">+1 min</button><select aria-label="Playback speed" className="bg-slate-800 p-1" value={s.speed} onChange={e=>r.setState(v=>({...v,speed:Number(e.target.value)}))}>{REPLAY_SPEEDS.map(v=><option key={v} value={v}>{v}×</option>)}</select><button className={button} onClick={()=>setAt(s.at-1800000)}>30 min earlier</button><label>At UTC <input aria-label="Replay timestamp UTC" type="datetime-local" step="1" className="bg-slate-800" value={new Date(s.at).toISOString().slice(0,19)} onChange={e=>{const at=Date.parse(e.target.value+'Z');if(Number.isFinite(at))setAt(at);}}/></label></div>
   <details><summary className="cursor-pointer">Replay domains ({r.domains.length}) · independent of live layer preferences</summary><div className="flex flex-wrap gap-2">{REPLAY_DOMAINS.map(d=><label key={d}><input type="checkbox" checked={r.domains.includes(d)} onChange={e=>r.setDomains(old=>e.target.checked?[...old,d]:old.length>1?old.filter(x=>x!==d):old)}/>{d}</label>)}</div></details>
   <p className="text-slate-400">Historical observations · Positions represent last retained observation at or before selected time; intervening path is not observed. Replay uses observation time; some records were received later.</p>
   <p className="text-slate-400">Retained: {r.coverage?.earliest?`${utc(r.coverage.earliest)} — ${utc(r.coverage.latest!)}`:'Not available'} · {r.coverage?`${r.coverage.retention.telemetry_days}d telemetry / ${r.coverage.retention.events_days}d events retention`:''}</p>
   {s.mode==='replay'&&<p>{r.busy?'Loading retained interval…':r.items.length?`${r.items.length} retained signals at this time`:'No retained observations for this time / viewport.'}</p>}
   {(r.truncated||r.coverage?.truncated)&&<p role="status" className="text-amber-300">Partial coverage: result limit reached. Narrow the viewport/domains/range; omitted data is unknown.</p>}{r.error&&<p role="alert" className="text-red-300">{r.error}</p>}
   {s.mode==='replay'&&<select aria-label="Historical observation" className="w-full bg-slate-800 p-1" value={r.selection?.id||''} onChange={e=>{const item=r.items.find(i=>i.id===e.target.value);if(item)choose(item);}}><option value="">Select a retained signal to inspect…</option>{r.items.slice(0,200).map(i=><option key={i.id} value={i.id}>{i.domain} · {i.name}{i.status?` · ${i.status}`:''}</option>)}</select>}
  </div>}
 </section>
 {s.mode==='replay'&&r.selection&&<aside aria-label="Historical evidence" className="absolute z-[460] left-14 top-24 w-[330px] max-w-[calc(100vw-100px)] max-h-[48vh] overflow-auto rounded border border-cyan-400/50 bg-[var(--bg-primary)]/95 text-[var(--text-primary)] p-3 font-mono text-xs space-y-2">
  <button className="float-right" aria-label="Close historical evidence" onClick={()=>r.select(null)}>×</button><div className="text-cyan-300">HISTORICAL OBSERVATION</div><strong>{r.selection.name}</strong><p>{r.selection.domain} · {utc(r.selection.from)}{r.selection.status?` · ${r.selection.status}`:''}</p><p>{r.selection.freshness} relative to replay time · current object names used for navigation</p>
  <div className="flex flex-wrap gap-2">{r.selection.object_id&&INVESTIGATION_ACTIONS.map(a=><button key={a.intent} className={button} onClick={()=>onObject(r.selection!.object_id!,a.intent)}>{a.label}</button>)}{r.selection.correlation?.related_object_ids?.map(id=><button key={id} className={button} onClick={()=>onObject(id,'related')}>Related object {id.slice(0,8)}</button>)}</div>
  {r.selection.observation&&<><p>Observed: {r.selection.observation.observed_at?utc(r.selection.observation.observed_at):'Not provided'}</p><p>Received: {utc(r.selection.observation.fetched_at)}</p><EvidenceView items={r.selection.observation.provenance}/><pre className="whitespace-pre-wrap break-words text-[10px]">{JSON.stringify(r.selection.observation.data,null,2)}</pre></>}
  {r.selection.correlation&&<><p>Historical status: {r.selection.correlation.status}</p><p>{r.selection.correlation.explanation||'Earlier evidence snapshot was not retained. Historical location and evidence are unknown.'}</p>{r.selection.correlation.evidence?.map((e,i)=><EvidenceView key={i} items={e.provenance}/>)}</>}
 </aside>}
 </>;
}
