'use client';
import {useLocale as useUILocale} from '@/lib/i18n';
import { useCallback, useEffect, useState } from 'react';
import { intelligenceRequest, displayTime, type Page, type SourceStatus } from '@/lib/intelligence';
import IntelligencePanelShell, { intelButton } from './IntelligencePanelShell';
const color: Record<string, string> = { HEALTHY: 'text-emerald-300', DEGRADED: 'text-amber-300', OFFLINE: 'text-red-300', STALE: 'text-orange-300', UNKNOWN: 'text-slate-400' };
export default function SourceHealthPanel({ onClose, healthyOnly, onHealthyOnly }: { onClose: () => void; healthyOnly: boolean; onHealthyOnly: (value: boolean) => void }) {
  const {t:uiText}=useUILocale();
  const [scope, setScope] = useState('all'), [category, setCategory] = useState(''), [status, setStatus] = useState('');
  const [items, setItems] = useState<SourceStatus[]>([]), [cursor, setCursor] = useState<string | null>(null), [busy, setBusy] = useState(false), [error, setError] = useState('');
  const load = useCallback(async (signal: AbortSignal, after?: string) => {
    setBusy(true); setError(''); const params = new URLSearchParams({ scope, limit: '100' }); if (category) params.set('category', category); if (status) params.set('status', status); if (after) params.set('cursor', after);
    try { const result = await intelligenceRequest<Page<SourceStatus>>(`sources?${params}`, signal); if (signal.aborted) return; setItems(old => after ? [...old, ...result.items] : result.items); setCursor(result.next_cursor); } catch (e) { if (!signal.aborted) setError(e instanceof Error ? e.message : 'Source health unavailable'); } finally { if (!signal.aborted) setBusy(false); }
  }, [scope, category, status]);
  useEffect(() => { const c = new AbortController(); const start = setTimeout(() => void load(c.signal), 0); const timer = setInterval(() => void load(c.signal), 60000); return () => { c.abort(); clearTimeout(start); clearInterval(timer); }; }, [load]);
  return <IntelligencePanelShell title={uiText("SOURCE HEALTH")} onClose={onClose}><div className="p-3 flex flex-wrap gap-3 text-xs border-b border-[var(--border-primary)]">
    <select aria-label={uiText("Source scope")} value={scope} onChange={e => setScope(e.target.value)} className="bg-[var(--bg-secondary)] p-2">{['all', 'provider', 'service', 'camera'].map(v => <option key={v} value={v}>{uiText(v)}</option>)}</select>
    <select aria-label={uiText("Source category")} value={category} onChange={e => setCategory(e.target.value)} className="bg-[var(--bg-secondary)] p-2"><option value="">{uiText("All categories")}</option>{['cctv', 'aircraft', 'maritime', 'weather', 'fire', 'earthquake', 'news', 'conflict', 'cyber', 'satellite', 'ontology', 'static', 'api'].map(v => <option key={v} value={v}>{uiText(v)}</option>)}</select>
    <select aria-label={uiText("Source status")} value={status} onChange={e => setStatus(e.target.value)} className="bg-[var(--bg-secondary)] p-2"><option value="">{uiText("All statuses")}</option>{Object.keys(color).map(v => <option key={v} value={v}>{uiText(v)}</option>)}</select>
    <button className={intelButton} disabled={busy} onClick={() => void load(new AbortController().signal)}>{uiText("Refresh")}</button><label className="flex items-center gap-2"><input type="checkbox" checked={healthyOnly} onChange={e => onHealthyOnly(e.target.checked)} />{" "}{uiText("CCTV: Healthy only")}</label>
  </div><div className="overflow-auto p-3 flex-1"><p className="text-xs text-slate-400 mb-3">{uiText("Provider/catalog checks and individual camera checks are separate. Healthy only shows cameras with a recent successful frame check; unknown cameras are excluded only when enabled. Open a camera to check it.")}</p>
    <p className="text-[11px] text-slate-400 mb-3">{uiText("Last 100 actual checks per source. Any consecutive failure → DEGRADED; 5 → OFFLINE. Recovery resets failures; a recent success rate below 80% remains DEGRADED. Freshness uses source timestamps, not cache hits.")}</p>
    {error && <p role="alert" className="text-red-300 text-xs">{error}</p>}{busy && <p role="status" className="text-xs">{uiText("Loading source health…")}</p>}
    <table className="w-full text-xs text-left border-collapse"><thead className="text-[var(--gold-primary)]"><tr>{['Source / category', 'Status / freshness', 'Success rate', 'Median latency', 'Last success', 'Last error / records'].map(h => <th className="p-2" key={h}>{uiText(h)}</th>)}</tr></thead><tbody>{items.map(s => <tr key={s.id} className="border-t border-[var(--border-primary)] align-top"><td className="p-2 max-w-64 break-words"><strong>{s.name}</strong><div className="text-slate-400">{uiText(s.category)} · {uiText(s.scope)}</div><details><summary className="cursor-pointer text-slate-400">{uiText("Check details")}</summary><div>{s.endpoint}</div><div>{uiText("Checked:")}{" "}{displayTime(s.last_checked_at)}</div><div>{uiText("Data:")}{" "}{displayTime(s.data_at)}</div><div>{uiText("Failures:")}{" "}{s.consecutive_failures}</div><div>{uiText("Next check after:")}{" "}{displayTime(s.next_check_at)}</div></details></td><td className="p-2"><div className={color[s.status]}>{uiText(s.status)}</div>{s.scope==='camera' && <div className="text-[10px] mt-1"><div>{uiText('Snapshot')}: {uiText(s.camera_media?.snapshot_status || 'UNKNOWN')}</div><div>{uiText('Video')}: {uiText(s.camera_media?.stream_status || 'UNKNOWN')}</div></div>}{s.credential_state && s.credential_state!=="NOT_REQUIRED" && <div className="text-amber-300">{uiText(s.credential_state)}</div>}<div className="text-slate-400">{uiText(s.freshness)}</div></td><td className="p-2">{s.success_rate == null ? uiText("Unknown") : `${Math.round(s.success_rate * 100)}%`}<div className="text-slate-400">{s.sample_count}{" "}{uiText("checks")}</div></td><td className="p-2">{s.median_latency_ms == null ? uiText("Unknown") : `${s.median_latency_ms} ms`}</td><td className="p-2">{displayTime(s.last_success_at)}</td><td className="p-2">{s.last_error_category || '—'}<div className="text-slate-400">{uiText("Records:")}{" "}{s.record_count ?? uiText("unknown")}</div></td></tr>)}</tbody></table>
    {!busy && !items.length && <p className="p-4 text-xs">{uiText("No checks match this filter yet. Monitoring starts with real requests; cameras are checked on demand.")}</p>}{cursor && items.length < 2000 && <button className={intelButton} disabled={busy} onClick={() => void load(new AbortController().signal, cursor)}>{uiText("Next sources")}</button>}
  </div></IntelligencePanelShell>;
}
