'use client';
import {useLocale as useUILocale} from '@/lib/i18n';
import {useEffect,useState,useMemo,type RefObject} from 'react';
import type {Map,GeoJSONSource,MapLayerMouseEvent,RasterTileSource} from 'maplibre-gl';
import {recordMatchesThreatLayer,worldSeed,type WorldRecord,type ProviderResult,type Bounds} from '@/lib/world/types';
import {mapFeatures,geometryFeatures,radarFrameAt,type RadarFrame} from '@/lib/world/map';
import type {InvestigationSeed} from '@/lib/ontology';
import type {InvestigationIntent} from '@/lib/investigation';
import InvestigationActions from './InvestigationActions';
import WeatherOverlay from './WeatherOverlay';
import {ensureReportSymbols} from '@/lib/air-threat/symbols';
interface Props {mapRef:RefObject<Map|null>;ready:boolean;layers:Record<string,boolean>;replayAt:number|null;onInvestigate:(seed:InvestigationSeed,intent:InvestigationIntent)=>void}
interface Result extends ProviderResult {next_cursor?:string|null;unlocated?:number;unlocated_records?:WorldRecord[];providers?:{provider:string;status:string;credential_state?:string;count:number;diagnostics?:Record<string,unknown>;future_records_omitted?:number}[]}
const EMPTY:WorldRecord[]=[];
export default function WorldLayers({mapRef,ready,layers,replayAt,onInvestigate}:Props){
  const {t:uiText}=useUILocale();
 const [viewport,setViewport]=useState<{b:Bounds;zoom:number}|null>(null),[infra,setInfra]=useState<Result>(),[reports,setReports]=useState<Result>(),[frames,setFrames]=useState<RadarFrame[]>([]),[selected,setSelected]=useState<WorldRecord|null>(null),[errors,setErrors]=useState<Record<string,string>>({}),[providers,setProviders]=useState<{id:string;status:string;message?:string}[]>([]),[expanded,setExpanded]=useState(false),[hours,setHours]=useState(1),[styleEpoch,setStyleEpoch]=useState(0);
 const infraKey=Object.keys(layers).filter(k=>k.startsWith('infra_')&&layers[k]).map(k=>k.slice(6)).sort().join(','),wxEnabled=Object.keys(layers).some(k=>k.startsWith('wx_')&&k!=='wx_radar'&&layers[k]),conflictEnabled=Object.keys(layers).some(k=>k.startsWith('conflict_')&&layers[k]),radarEnabled=!!layers.wx_radar;
 const active=!!infraKey||wxEnabled||conflictEnabled||radarEnabled;
 useEffect(()=>{const map=mapRef.current;if(!ready||!map)return;const update=()=>{const b=map.getBounds();const west=Math.max(-180,b.getWest()),east=Math.min(180,b.getEast()),south=Math.max(-85,b.getSouth()),north=Math.min(85,b.getNorth());setViewport({b:[west,south,east,north],zoom:map.getZoom()});};update();map.on('moveend',update);const style=()=>{setStyleEpoch(n=>n+1);update();};map.on('style.load',style);return()=>{map.off('moveend',update);map.off('style.load',style);};},[ready,mapRef]);
 const bbox=viewport?.b.map(n=>n.toFixed(3)).join(',')||'';
 const weatherBbox=viewport?.b.map(n=>n.toFixed(6)).join(',')||'';
 useEffect(()=>{
  if(!active)return;const c=new AbortController();void fetch('/api/world/providers',{signal:c.signal}).then(r=>r.json()).then(r=>setProviders(r.providers||[])).catch(()=>{});return()=>c.abort();
 },[active]);
 useEffect(()=>{
  if(!bbox||!active)return;const c=new AbortController(),retries:ReturnType<typeof setTimeout>[]=[];
  const load=async(kind:string,q:string,save:(r:Result)=>void,retried=false)=>{try{const r=await fetch(`/api/world/${kind}?${q}`,{signal:c.signal});const body=await r.json();if(!r.ok){if((r.status===429||r.status>=500)&&!retried&&!c.signal.aborted)retries.push(setTimeout(()=>void load(kind,q,save,true),r.status===429?30000:2000));throw new Error(body.error==='PROVIDER_BACKOFF'?'Provider cooling down; retrying automatically':body.error||'Unavailable');}if(!c.signal.aborted){save(body);setErrors(e=>({...e,[kind]:body.truncated?'Partial coverage: result limit reached':''}));}}catch(e){if(!c.signal.aborted){save({records:[],status:'UNAVAILABLE'});setErrors(v=>({...v,[kind]:e instanceof Error?e.message:'Unavailable'}));}}};
  const tick=()=>{if(replayAt!==null)return;if(infraKey)void load('infrastructure',`bbox=${bbox}&categories=${infraKey}`,setInfra);if(conflictEnabled)void load('conflicts',`bbox=${bbox}&hours=${hours}`,setReports);};
  const delay=setTimeout(tick,800),timer=setInterval(tick,120000);return()=>{clearTimeout(delay);clearInterval(timer);retries.forEach(clearTimeout);c.abort();};
 },[bbox,infraKey,conflictEnabled,active,replayAt,hours]);
 useEffect(()=>{if(!radarEnabled)return;const c=new AbortController();const load=()=>void fetch('/api/world/radar',{signal:c.signal}).then(r=>r.json()).then(r=>{if(!c.signal.aborted){if(Array.isArray(r.frames))setFrames(r.frames);setErrors(e=>({...e,radar:r.error||''}));}}).catch(()=>{if(!c.signal.aborted)setErrors(e=>({...e,radar:'Radar metadata unavailable; last successful frame retained'}));});load();const t=setInterval(load,120000);return()=>{clearInterval(t);c.abort();};},[radarEnabled]);
 const objects=useMemo(()=>replayAt!==null?EMPTY:[...(infraKey?infra?.records||[]:[]),...(conflictEnabled?reports?.records.filter(r=>Object.entries(layers).some(([k,v])=>v&&recordMatchesThreatLayer(r,k)))||[]:[])],[infra,infraKey,reports,conflictEnabled,layers,replayAt]);
 const frame=radarEnabled?radarFrameAt(frames,replayAt??frames.at(-1)?.time??0):null;
 useEffect(()=>{
  const map=mapRef.current;if(!ready||!map)return;
  for(const id of ['world-assets','world-geometry'])if(!map.getSource(id))map.addSource(id,{type:'geojson',data:{type:'FeatureCollection',features:[]},...(id==='world-assets'?{cluster:true,clusterMaxZoom:8,clusterRadius:40}:{})});
  if(!map.getLayer('world-geometry'))map.addLayer({id:'world-geometry',type:'line',source:'world-geometry',paint:{'line-color':'#d4af37','line-width':2,'line-opacity':.65}});
  if(!map.getLayer('world-clusters')){map.addLayer({id:'world-clusters',type:'circle',source:'world-assets',filter:['has','point_count'],paint:{'circle-color':'#b69a48','circle-radius':15}});map.addLayer({id:'world-cluster-labels',type:'symbol',source:'world-assets',filter:['has','point_count'],layout:{'text-field':['get','point_count_abbreviated'],'text-font':['Noto Sans Regular'],'text-size':11}});}
  ensureReportSymbols(map);
  if(!map.getLayer('world-assets'))map.addLayer({id:'world-assets',type:'circle',source:'world-assets',filter:['!',['has','point_count']],paint:{'circle-color':['get','color'],'circle-radius':['case',['==',['get','domain'],'conflict'],13,6],'circle-opacity':['coalesce',['get','opacity'],1],'circle-stroke-color':'#fff','circle-stroke-width':1}});
  if(!map.getLayer('world-report-sound-area'))map.addLayer({id:'world-report-sound-area',type:'circle',source:'world-assets',filter:['all',['!',['has','point_count']],['==',['get','acoustic'],true]],paint:{'circle-radius':32,'circle-color':'#67e8f9','circle-opacity':.14,'circle-stroke-color':'#67e8f9','circle-stroke-opacity':.5,'circle-stroke-width':1}},'world-assets');
  if(!map.getLayer('world-report-icons'))map.addLayer({id:'world-report-icons',type:'symbol',source:'world-assets',filter:['all',['!',['has','point_count']],['==',['get','domain'],'conflict']],layout:{'icon-image':['get','icon'],'icon-size':.7,'icon-allow-overlap':true},paint:{'icon-opacity':['coalesce',['get','opacity'],1]}});
  (map.getSource('world-assets') as GeoJSONSource).setData(mapFeatures(objects));(map.getSource('world-geometry') as GeoJSONSource).setData(geometryFeatures(objects));
  map.getContainer().dataset.worldAssetPoints=String(mapFeatures(objects).features.length);
  const click=(e:MapLayerMouseEvent)=>{const id=e.features?.[0]?.properties?.id;const r=objects.find(r=>r.id===id);if(r)setSelected(r);};
  for(const id of ['world-assets','world-geometry','world-report-icons'])map.on('click',id,click);
  return()=>{for(const id of ['world-assets','world-geometry','world-report-icons'])map.off('click',id,click);};
 },[ready,mapRef,objects,styleEpoch]);
 useEffect(()=>{const map=mapRef.current;if(!ready||!map)return;if(!frame){if(map.getLayer('world-radar'))map.removeLayer('world-radar');if(map.getSource('world-radar'))map.removeSource('world-radar');return;}
  const tiles=[`${window.location.origin}/api/world-radar/${frame.time}/{z}/{x}/{y}`];
  if(map.getSource('world-radar'))(map.getSource('world-radar') as RasterTileSource).setTiles(tiles);else {map.addSource('world-radar',{type:'raster',tiles,tileSize:256,maxzoom:7,attribution:'<a href="https://www.rainviewer.com/">RainViewer</a>'});map.addLayer({id:'world-radar',type:'raster',source:'world-radar',paint:{'raster-opacity':.55,'raster-fade-duration':0}},map.getLayer('world-assets')?'world-assets':undefined);}
 },[ready,mapRef,frame,styleEpoch]);
 if(!active&&!selected)return null;
 return <aside aria-label={uiText("World data layers")} className="absolute left-16 bottom-28 z-40 w-72 max-w-[calc(100vw-120px)] max-h-[55vh] overflow-auto rounded border border-amber-300/30 bg-slate-950/95 p-3 break-words text-[11px] font-mono text-slate-200 shadow-xl">
  <button className="text-amber-300 tracking-widest w-full text-left" onClick={()=>setExpanded(v=>!v)}>{uiText("WORLD DATA")}{" "}{expanded?'−':'+'}</button>
  {conflictEnabled&&replayAt===null&&<div className="mt-2 space-y-1"><label>{uiText('Report window')} <select aria-label={uiText('Report window')} className="bg-slate-900 border border-slate-600" value={hours} onChange={e=>setHours(Number(e.target.value))}>{[1,6,24].map(n=><option key={n} value={n}>{n} {uiText('hours')}</option>)}</select></label><p>{uiText('Retained reports in view:')} {objects.filter(r=>r.domain==='conflict'&&r.lat!==null).length}</p>{['conflict_drone','conflict_missile','conflict_air','conflict_other'].filter(k=>layers[k]).map(k=><p key={k}>{uiText(({conflict_drone:'Drone reports',conflict_missile:'Missile reports',conflict_air:'Air alerts / strikes',conflict_other:'Other conflict reports'} as Record<string,string>)[k])}: {reports?.records.filter(r=>recordMatchesThreatLayer(r,k)).length||0}</p>)}{reports?.status==='AVAILABLE'&&!reports.records.length&&<p className="text-amber-200">{uiText('No retained reports in this area/time. This is not ALL CLEAR.')}</p>}{!!reports?.unlocated&&<p>{uiText('Global reports without a verified area:')} {reports.unlocated}</p>}<p className="text-slate-400">{uiText('Icons denote source claims, not detected objects. Cyan halos mark sound-report areas, not audibility or a danger radius.')}</p><p className="text-slate-400">{uiText('Official civil-defense alerts take priority.')}</p>{reports?.truncated&&<p className="text-amber-200">{uiText('Result limit reached. Narrow the area or time window.')}</p>}</div>}
  {replayAt!==null&&<p className="my-2 text-cyan-300">{uiText("REPLAY · retained observations only; current model grid hidden.")}</p>}
  {infraKey&&<p>{uiText("Infrastructure:")}{" "}{replayAt===null?infra?.records.length||0:'retained'} · © <a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noreferrer">{uiText("OSM contributors")}</a></p>}
  <WeatherOverlay mapRef={mapRef} ready={ready} bbox={weatherBbox} zoom={viewport?.zoom??5} enabled={wxEnabled} layers={layers} replayAt={replayAt} onSelect={setSelected}/>
  {radarEnabled&&<p className="my-2"><a href="https://www.rainviewer.com/" target="_blank" rel="noreferrer">RainViewer</a> · {frame?new Date(frame.time).toUTCString():'Radar imagery unavailable for selected replay time'}{" "}{uiText("· Blue: weak → intense reflectivity (dBZ), not ground rain measurement")}</p>}
  {Object.entries(errors).filter(([k,v])=>v&&(k==='infrastructure'?infraKey:k==='weather'?wxEnabled:k==='radar'?radarEnabled:conflictEnabled)).map(([k,v])=><p key={k} className="text-orange-300">{k}: {v}</p>)}
  {expanded&&<div className="border-t border-slate-700 mt-2 pt-2">{providers.map(p=><p key={p.id} title={p.message}>{p.id}: {p.status}</p>)}{reports?.providers?.map(p=><p key={p.provider}>{p.provider}: {p.status} · {p.credential_state||''} · {p.count}{!!p.future_records_omitted && ` · ${p.future_records_omitted} future timestamps omitted`}</p>)}{reports?.providers?.filter(p=>p.diagnostics).map(p=><details key={`diagnostic:${p.provider}`} className="my-2"><summary>{p.provider} · {uiText('Ingestion diagnostics')}</summary><pre className="whitespace-pre-wrap break-all">{JSON.stringify(p.diagnostics,null,2)}</pre></details>)}{replayAt===null&&[...objects.slice(0,6),...(conflictEnabled?reports?.unlocated_records?.slice(0,4)||[]:[])].map(r=><button key={r.id} className="block text-left py-1 underline" onClick={()=>{setSelected(r);if(r.lat!==null&&r.lon!==null)mapRef.current?.flyTo({center:[r.lon,r.lat],zoom:Math.max(8,mapRef.current.getZoom())});}}>{r.name}{r.lat===null?' · no source coordinates':''}</button>)}</div>}
  {selected&&<div className="mt-3 border-t border-slate-600 pt-2"><button className="float-right p-1" aria-label={uiText("Close world object")} onClick={()=>setSelected(null)}>×</button><strong>{selected.name}</strong><p className="text-amber-200">{selected.domain==='conflict'?'REPORTED SIGNAL · not confirmed causation':selected.evidence_state}</p><p>{selected.provider} · {selected.location_precision}</p><p>{uiText("Source time:")}{" "}{selected.observed_at||uiText("Not provided")}</p><p>{uiText("Fetched:")}{" "}{selected.fetched_at}</p><p>{uiText("Confidence:")}{" "}{selected.confidence??uiText("Not provided")}</p><p>{selected.extraction_method}</p>{typeof selected.properties.original_text==='string'&&<p className="whitespace-pre-wrap border-l-2 border-slate-600 pl-2">{selected.properties.original_text}</p>}<p>{selected.geometry_precision==='representative'?'Representative location; no exact proximity claim':''}</p><a className="underline" href={selected.url} target="_blank" rel="noreferrer">{uiText("Source record")}</a><dl className="my-2">{Object.entries(selected.properties).filter(([,v])=>v!==null&&typeof v!=='object').slice(0,20).map(([k,v])=><div key={k}>{k}: {String(v).slice(0,150)}</div>)}</dl><InvestigationActions entity={{}} seed={worldSeed(selected)} onInvestigate={onInvestigate}/></div>}
 </aside>;
}
